### Numpy 배열의 연산

#### 리스트 연산과 Numpy 배열의 연산 비교:

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]

`+`: 배열이 이어짐(문자열 +)

In [3]:
a + a

[1, 2, 3, 1, 2, 3]

`*` 횟수만큼 반복

In [4]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

`np.array` 

In [5]:
b = np.array([1, 2, 3])

In [6]:
b*3

array([3, 6, 9])

`+` array 끼리 수치를 더할 수 있음

In [7]:
b + b

array([2, 4, 6])

In [8]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### Numpy 배열의 연산:

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [10]:
a+b

array([5, 7, 9])

In [11]:
a-b

array([-3, -3, -3])

In [12]:
a*b

array([ 4, 10, 18])

In [13]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

#### 연산의 벡터화 (universal function):

In [14]:
x = np.array([0, 1, 2, 3, 4, 5])

`pow(10,x)` 10의 x승 (`10**x`)

In [15]:
pow(10, x)

array([     1,     10,    100,   1000,  10000, 100000], dtype=int32)

In [16]:
x**3

array([  0,   1,   8,  27,  64, 125], dtype=int32)

`np.sqrt()` 제곱근 

In [17]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

`np.exp()` 자연상수 *e*

In [18]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

`np.cumsum()` 누적합

In [19]:
np.cumsum(x)

array([ 0,  1,  3,  6, 10, 15], dtype=int32)

#### Numpy가 제공하는 함수:

`randint` 랜덤 정수를 만들어라

In [20]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)

고유한 값(unique)만 불러온다

In [21]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.median(a)

5.0

In [23]:
np.sum(a)

5485

`round(,2)` 셋째 자리에서 반올림.

In [24]:
np.round(np.var(a),2)

8.19

In [25]:
np.round(np.mean(a),2)

5.48

In [26]:
np.round(np.std(a),2)

2.86

In [27]:
np.max(a)

10

In [28]:
np.min(a)

1

#### 배열의 메서드로 제공되는 함수:

In [29]:
x=np.arange(1,11)

In [30]:
x.sum()

55

In [31]:
x.mean()

5.5

In [32]:
x.std()

2.8722813232690143

In [33]:
x.var()

8.25

In [34]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [35]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(y.mean(axis=0))

[4. 5. 6.]


In [37]:
print(y.mean(axis=1))

[2. 5. 8.]


In [38]:
z = np.random.randint(10,size=1000)

In [39]:
z.max()

9

In [40]:
z.min()

0

`z가 5초과하는 값`만 찾아라`.`그들에 대한 `sum()[합]`을 구하라

In [41]:
(z > 5).sum()

392

In [42]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

집합은 `중복`을 허용하지 않기 때문에 z의 중복된 원소들을 간추려주고
`sorted`으로 오름차순으로 정리하라

In [43]:
sorted(set(z))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [47]:
a.max()

7

a 중 가장 큰 값인 7의 `위치(0,1,2,3,4번째)`

In [45]:
a.argmax()

4

In [48]:
a.min()

-3

a 중 가장 작은 값인 -3의 `위치(0,1)번째`

In [46]:
a.argmin()

1